# Numpy and Pandas

### 1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix. (Score:1)

In [17]:
import numpy as np
import pandas as pd

In [5]:
Arr1=np.array([1,2,3,4,5,6,7,8,9,10])
Arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
Rearray=Arr1.reshape(2,5)
Rearray

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### 2. Create a numpy array containing the numbers from 1 to 20, and then extract the elements between the 5th and 15th index. (Score:1)

In [8]:
Arr2=np.arange(1,21,1)
Arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [9]:
print(Arr2[4:15])

[ 5  6  7  8  9 10 11 12 13 14 15]


### 3. How to compute the mean, median, and standard deviation of a numpy array?Use the array you created above (Score 1)

In [11]:
print(np.mean(Arr2))

10.5


In [12]:
print(np.median(Arr2))

10.5


In [13]:
print(np.std(Arr2))

5.766281297335398


### 4. Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of shape (4,). Subtract y from each row of x using broadcasting. (Score: 2)

In [14]:
x=np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])
x

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [15]:
y=np.array([10,20,30,40])
y

array([10, 20, 30, 40])

In [16]:
print(x-y)

[[ 0  0  0  0]
 [40 40 40 40]
 [80 80 80 80]]


### 5. Create a dataframe with the following columns: name, age, and gender. The dataframe should have 10 rows of data. (Score: 2)

In [26]:
Survey={'Name':['Anil','Arun','Meena','Amal','Kavitha','Suresh','Arjun','Devi','Vijesh','Medha'],'Age':[23,30,23,67,29,23,26,24,34,27],'Gender':['Male','Male','Female','Male','Female','Male','Male','Female','Male','Female']}
df=pd.DataFrame(Survey)
df


,Name,Age,Gender
0,Anil,23,Male
1,Arun,30,Male
2,Meena,23,Female
3,Amal,67,Male
4,Kavitha,29,Female
5,Suresh,23,Male
6,Arjun,26,Male
7,Devi,24,Female
8,Vijesh,34,Male
9,Medha,27,Female


#### 1) Add a new column to the data frame created in question 1, called occupation.
The values for this column should be Programmer, Manager, and Analyst,
corresponding to the rows in the dataframe. (Score: 1)

In [27]:
df['Occupation']=['Manager','Analyst','Programmer','Analyst','Programmer','Analyst','Analyst','Programmer','Manager','Programmer']
df

,Name,Age,Gender,Occupation
0,Anil,23,Male,Manager
1,Arun,30,Male,Analyst
2,Meena,23,Female,Programmer
3,Amal,67,Male,Analyst
4,Kavitha,29,Female,Programmer
5,Suresh,23,Male,Analyst
6,Arjun,26,Male,Analyst
7,Devi,24,Female,Programmer
8,Vijesh,34,Male,Manager
9,Medha,27,Female,Programmer


#### 2) Select the rows of the dataframe where the age is greater than or equal to 30.
(Score: 1)

In [28]:
df[df['Age']>=30]


,Name,Age,Gender,Occupation
1,Arun,30,Male,Analyst
3,Amal,67,Male,Analyst
8,Vijesh,34,Male,Manager


#### 3) Convert this dataframe to a CSV file and read that CSV file, and finally display the contents. (Score: 1)

In [30]:
df.to_csv("Survey.csv",index=False)

In [31]:
New_df=pd.read_csv("Survey.csv")


In [32]:
print(New_df)

      Name  Age  Gender  Occupation
0     Anil   23    Male     Manager
1     Arun   30    Male     Analyst
2    Meena   23  Female  Programmer
3     Amal   67    Male     Analyst
4  Kavitha   29  Female  Programmer
5   Suresh   23    Male     Analyst
6    Arjun   26    Male     Analyst
7     Devi   24  Female  Programmer
8   Vijesh   34    Male     Manager
9    Medha   27  Female  Programmer
